---
- name: web install
  hosts: all
  become: yes
  vars:
    dist: "{{ 'amazon' if ansible_distribution == 'Amazon'
                    else 'ubuntu' if ansible_distribution == 'Ubuntu'
                }}"

  tasks:
    - name: web installation
      include_tasks: "{{ dist }}.yml"
  
    - name: PRINT IP ADDRESS
      debug:
        msg:
          - "NodeName : {{ ansible_nodename }}"
          - "eth0 : {{ ansible_eth0.ipv4.address }}"
